routes:
collections:
  /articles/:
    permalink: /{slug}/
    template: index
  /:
    permalink: /{slug}/
    template: home
    data: page.home
taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
